<?php

/**
 * Implements hook_form_alter().
 */
function custom_form_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_login_form') {

    $form['name']['#weight'] = 10;
    $form['pass']['#weight'] = 1;

    $form['name']['#description'] = t('Zadej uzivatelske jmeno.');
    $form['custom_form_date'] = [
      '#type' => 'date',
      '#title' => t('Datum'),
      '#description' => t('Zadej datum'),
      '#required' => TRUE,
    ];
    $form['#validate'][] = 'custom_form_validate';
  }
}


function custom_form_validate(&$form, &$form_state) {
  $form_values = $form_state->getValues();
//  ksm($form_values);

  if ($form_values['custom_form_date'] != "2018-11-30") {
    $form_state->setErrorByName('custom_form_date', t('Musis se registrovat dnes.'));
  }

}